### ISSUE TITLE
Changing the font size

### ISSUE THREAD

**Issue by Ektaynot** [genzyy/anime-cli#1]

**Comment by rishitxyz** [comment]
Can you elaborate the issue more please?

**Comment by rishitxyz** [comment]
I think you are talking about the font size that I have used for the CLI app.
If yes then the font size actually depends on your terminal. the results will be displayed according to the font size you have set in your terminal.
If you want to reopen this issue feel free to do it.

**Comment by Ektaynot** [comment]
ok thanks
