### ISSUE TITLE
Help message displays incorrect options

### ISSUE THREAD

**Issue by koolskateguy89** [genzyy/anime-cli#10]
The [help option in the help message](https://github.com/genzyy/anime-cli/blob/459b4501dacc550b0add97259e726d13dee6f606/index.js#L59) shows `-help` but if you run `anime-cli -help` it doesn't show the help message (should be `--help`).

Also the short-hand options for [help](https://github.com/genzyy/anime-cli/blob/459b4501dacc550b0add97259e726d13dee6f606/index.js#L67) and [version](https://github.com/genzyy/anime-cli/blob/459b4501dacc550b0add97259e726d13dee6f606/index.js#L71) are incorrect (and technically so are the long options (should be `--help` instead of `help` etc.).

- Running `anime-cli -h` returns a search, it doesn't show the help message.
- Running `anime-cli -v` returns a search, not the version.

Both just above will be 'fixed' by changing the options shown in the help message to
`--help, -h`
and
`--version, -v`

**Comment by rishitxyz** [comment]
Fixed.
Thanks for the info!
