### ISSUE TITLE
Incorrect config file path in README

### ISSUE THREAD

**Issue by koolskateguy89** [genzyy/anime-cli#8]
According to the README, the config file ("in Linux/MacOS") is at 
```
./config/configstore/@genzyy/anime-cli.json
```
but this is a **relative path** (and incorrect).

The general path, according to [configstore](https://www.npmjs.com/package/configstore) is `~/.config/configstore/some-id.json` thus the actual config file path:
```
~/.config/configstore/@genzyy/anime-cli.json
```

**Comment by rishitxyz** [comment]
Fixed.
Sorry for the typo!
